// build.mjs — precompiles the Koutsi app sources into one minified bundle per page.
//
// The pages used to ship react.development.js plus @babel/standalone and transpile ~150 kB
// of JSX in the browser on every load — several seconds of blank screen on a coach's phone
// in a tennis hall. This turns that into a single pre-built script.
//
//   npm run build
//
// Output goes to dist/ and IS committed, so Vercel keeps serving the repo as plain static
// files with no build step. Re-run this after editing anything under lib/.
//
// Each source file is wrapped in its own IIFE rather than concatenated flat: the files are
// classic global scripts that already talk to each other through window.*, and separate
// scopes keep same-named locals in different files from colliding.

import { build } from 'esbuild';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const outDir = join(root, 'dist');

// Load order matters: auth defines the Supabase client the data layer uses, the data layer
// defines the helpers the UI kit and the apps call, and the app file mounts React last.
const PAGES = {
  'koutsi-valmentaja': [
    'lib/koutsi-auth.jsx',
    'lib/koutsi-data.js',
    'lib/koutsi-theme-import.js',
    'lib/koutsi-qr.js',
    'lib/koutsi-ui.jsx',
    'lib/koutsi-timeline.jsx',
    'lib/koutsi-valmentaja-app.jsx',
  ],
  'koutsi-pelaaja': [
    'lib/koutsi-auth.jsx',
    'lib/koutsi-data.js',
    'lib/koutsi-qr.js',
    'lib/koutsi-ui.jsx',
    'lib/koutsi-timeline.jsx',
    'lib/koutsi-pelaaja-app.jsx',
  ],
  // The demo runs the REAL app files. koutsi-data.js loads first for its pure helpers,
  // then koutsi-demo-backend.jsx overwrites every Supabase-backed function with an
  // in-memory version and shims auth — so the demo can never drift from the product.
  'koutsi-valmentaja-demo': [
    'lib/koutsi-demo-role-coach.js',
    'lib/koutsi-data.js',
    'lib/koutsi-demo-backend.jsx',
    'lib/koutsi-theme-import.js',
    'lib/koutsi-qr.js',
    'lib/koutsi-ui.jsx',
    'lib/koutsi-timeline.jsx',
    'lib/koutsi-valmentaja-app.jsx',
  ],
  'koutsi-pelaaja-demo': [
    'lib/koutsi-demo-role-player.js',
    'lib/koutsi-data.js',
    'lib/koutsi-demo-backend.jsx',
    'lib/koutsi-qr.js',
    'lib/koutsi-ui.jsx',
    'lib/koutsi-timeline.jsx',
    'lib/koutsi-pelaaja-app.jsx',
  ],
  'koutsi-landing': [
    'lib/koutsi-phone.jsx',
    'lib/koutsi-landing.jsx',
  ],
};

async function transform(file) {
  const source = await readFile(join(root, file), 'utf8');
  const bundlesDependencies = file === 'lib/koutsi-theme-import.js';
  const result = await build({
    stdin: {
      contents: source,
      loader: file.endsWith('.jsx') ? 'jsx' : 'js',
      sourcefile: file,
      resolveDir: root,
    },
    write: false,
    bundle: bundlesDependencies,
    minify: true,
    format: 'iife',
    target: ['es2019', 'safari14'],
    legalComments: 'none',
  });
  return result.outputFiles[0].text;
}

async function buildPage(name, files) {
  const parts = [];
  for (const file of files) {
    parts.push(`/* ${file} */\n${await transform(file)}`);
  }
  const banner = `/* ${name} — generated by build.mjs, do not edit. Source: ${files.join(', ')} */\n`;
  const bundle = banner + parts.join('\n');
  await writeFile(join(outDir, `${name}.js`), bundle, 'utf8');
  return bundle.length;
}

// ── demon kattavuustarkistus ────────────────────────────────────────────────
// Demo ajaa oikeaa sovellusta valedatakerroksen päällä. Jos koutsi-data.js saa
// uuden Supabase-funktion jota koutsi-demo-backend.jsx ei korvaa, demo kaatuu
// vasta ajossa ("rpc is not a function"). Kaadetaan build sen sijaan heti.
async function assertDemoCoverage() {
  const read = (f) => readFile(join(root, f), 'utf8');
  const data = await read('lib/koutsi-data.js');
  const demo = await read('lib/koutsi-demo-backend.jsx');
  const appSources = await Promise.all(
    ['lib/koutsi-valmentaja-app.jsx', 'lib/koutsi-pelaaja-app.jsx', 'lib/koutsi-ui.jsx', 'lib/koutsi-timeline.jsx'].map(read),
  );

  // paloittele koutsi-data.js funktioiksi, jotta nähdään mitkä koskevat Supabaseen
  const marks = [...data.matchAll(/^(?:async\s+)?function\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(/gm)];
  const backed = new Set();
  marks.forEach((m, i) => {
    const body = data.slice(m.index, i + 1 < marks.length ? marks[i + 1].index : data.length);
    if (body.includes('koutsiSupabase')) backed.add(m[1]);
  });

  const used = new Set();
  appSources.forEach((src) => {
    for (const m of src.matchAll(/window\.([A-Za-z_][A-Za-z0-9_]*)/g)) used.add(m[1]);
  });
  const overridden = new Set([...demo.matchAll(/window\.([A-Za-z_][A-Za-z0-9_]*)\s*=/g)].map((m) => m[1]));

  const missing = [...used].filter((n) => backed.has(n) && !overridden.has(n)).sort();
  if (missing.length > 0) {
    console.error('\nDemo ei kata kaikkia datakerroksen funktioita.');
    console.error('Lisaa nama lib/koutsi-demo-backend.jsx:aan:\n');
    missing.forEach((n) => console.error('  - ' + n));
    console.error('');
    process.exit(1);
  }
  console.log(`demo kattaa ${[...used].filter((n) => backed.has(n)).length}/${[...used].filter((n) => backed.has(n)).length} datakerroksen funktiota`);
}

await assertDemoCoverage();

await mkdir(outDir, { recursive: true });
for (const [name, files] of Object.entries(PAGES)) {
  const bytes = await buildPage(name, files);
  console.log(`dist/${name}.js  ${(bytes / 1024).toFixed(1)} kB`);
}
