// build.mjs — precompiles the Koutsi app sources into one minified bundle per page.
//
// The pages used to ship react.development.js plus @babel/standalone and transpile ~150 kB
// of JSX in the browser on every load — several seconds of blank screen on a coach's phone
// in a tennis hall. This turns that into a single pre-built script.
//
//   npm run build
//
// Output goes to dist/ and IS committed, so Vercel keeps serving the repo as plain static
// files with no build step. Re-run this after editing anything under lib/.
//
// Each source file is wrapped in its own IIFE rather than concatenated flat: the files are
// classic global scripts that already talk to each other through window.*, and separate
// scopes keep same-named locals in different files from colliding.

import { build } from 'esbuild';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const outDir = join(root, 'dist');

// Load order matters: auth defines the Supabase client the data layer uses, the data layer
// defines the helpers the UI kit and the apps call, and the app file mounts React last.
const PAGES = {
  'koutsi-valmentaja': [
    'lib/koutsi-auth.jsx',
    'lib/koutsi-data.js',
    'lib/koutsi-qr.js',
    'lib/koutsi-ui.jsx',
    'lib/koutsi-valmentaja-app.jsx',
  ],
  'koutsi-pelaaja': [
    'lib/koutsi-auth.jsx',
    'lib/koutsi-data.js',
    'lib/koutsi-qr.js',
    'lib/koutsi-ui.jsx',
    'lib/koutsi-timeline.jsx',
    'lib/koutsi-pelaaja-app.jsx',
  ],
};

async function transform(file) {
  const source = await readFile(join(root, file), 'utf8');
  const result = await build({
    stdin: {
      contents: source,
      loader: file.endsWith('.jsx') ? 'jsx' : 'js',
      sourcefile: file,
      resolveDir: root,
    },
    write: false,
    bundle: false,
    minify: true,
    format: 'iife',
    target: ['es2019', 'safari14'],
    legalComments: 'none',
  });
  return result.outputFiles[0].text;
}

async function buildPage(name, files) {
  const parts = [];
  for (const file of files) {
    parts.push(`/* ${file} */\n${await transform(file)}`);
  }
  const banner = `/* ${name} — generated by build.mjs, do not edit. Source: ${files.join(', ')} */\n`;
  const bundle = banner + parts.join('\n');
  await writeFile(join(outDir, `${name}.js`), bundle, 'utf8');
  return bundle.length;
}

await mkdir(outDir, { recursive: true });
for (const [name, files] of Object.entries(PAGES)) {
  const bytes = await buildPage(name, files);
  console.log(`dist/${name}.js  ${(bytes / 1024).toFixed(1)} kB`);
}
